version: '3'

volumes:
  pg_data_production:
  static_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  
  backend:
    image: ladank/taski_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
    environment:
      - SECRET_KEY
  
  frontend:
    image: ladank/taski_frontend  
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  
  gateway:
    build: ./gateway/
    env_file: .env
    depends_on:
      - backend
    volumes:
      - static:/staticfiles
    ports:
      - 8000:80
